<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Casko.Authentication.NemLogin3.Web" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
    <PackageReference Include="Umbraco.Cms.Web.Website" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\App_Plugins\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
